logging:
  level:
    ROOT: debug
    jp.gmo.auth: debug
  file:
    path: log
server:
  port: 8080

spring:
  application:
    name: auth-service
  profiles:
    active: dev

jwt:
  base64-secret: MTIxZGJkMGFlODM1Zjg2MGNmZmYwNTBkNmVmM2Q4MGRlMzk4NjNkOWQyZGJlNjViYTI4NWEzMTg5YWI2ZDYzZjA1MTE3MTg4ZWM2YTAyY2ExYTVjZTYwZTRkYWIyYmUxNTBhZTM2NjBlYTA0OWU0NTY0MmM4OGQ2NjU2ZmFmMGI=
  token-validity: 86400
  
gmo:
  url:
    getAccountInfo: http://localhost:8081/api/v1/user/get-account